# -*- coding: utf-8 -*-
# Authors: Elizaveta Sineva, Sara Chilson
"""
Dictionaries converting language abbreviations to full language name and vice
versa. The FULL2ABBR dictionary converts full language name to the abbreaviations
used specifically in Aspell 0.60.8.1.
"""

ABBR2FULL = {'af': 'afrikaans', 
             'sq': 'albanian', 
             'ar': 'arabic', 
             'hy': 'armenian', 
             'bn': 'bengali',
             'bg': 'bulgarian', 
             'eu': 'basque', 
             'br': 'breton', 
             'ca': 'catalan', 
             'hr': 'croatian', 
             'cs': 'czech', 
             'da': 'danish', 
             'nl': 'dutch', 
             'en': 'english', 
             'eo': 'esperanto', 
             'et': 'estonian', 
             'fi': 'finnish', 
             'fr': 'french', 
             'gl': 'galician', 
             'ka': 'georgian', 
             'de': 'german', 
             'el': 'greek', 
             'he': 'hebrew', 
             'hi': 'hindi', 
             'hu': 'hungarian', 
             'is': 'icelandic', 
             'id': 'indonesian', 
             'it': 'italian', 
             'kk': 'kazakh', 
             'lv': 'latvian', 
             'lt': 'lithuanian', 
             'mk': 'macedonian', 
             'ms': 'malay', 
             'ml': 'malayalam', 
             'no': 'norwegian', 
             'fa': 'persian', 
             'pl': 'polish', 
             'pt_br': 'portuguese_brazil', 
             'pt': 'portuguese_portugal',
             'pt_pt': 'portuguese_portugal', 
             'ro': 'romanian', 
             'ru': 'russian', 
             'sr': 'serbian', 
             'sk': 'slovak', 
             'sl': 'slovenian', 
             'es': 'spanish', 
             'sv': 'swedish', 
             'tl': 'tagalog', 
             'ta': 'tamil', 
             'te': 'telugu', 
             'tr': 'turkish', 
             'uk': 'ukrainian', 
             'ur': 'urdu'}


# Abbreviations as used in Aspell
FULL2ABBR = {'afrikaans': 'af',
             'albanian': 'sq',
             'arabic': 'ar',
             'armenian': 'hy',
             'bengali': 'bn',
             'bulgarian': 'bg',
             'basque': 'eu',
             'breton': 'br',
             'catalan': 'ca',
             'croatian': 'hr',
             'czech': 'cs',
             'danish': 'da',
             'dutch': 'nl',
             'english': 'en',
             'esperanto': 'eo',
             'estonian': 'et',
             'finnish': 'fi',
             'french': 'fr',
             'galician': 'gl',
             'georgian': 'ka',
             'german': 'de',
             'greek': 'el',
             'hebrew': 'he',
             'hindi': 'hi',
             'hungarian': 'hu',
             'icelandic': 'is',
             'indonesian': 'id',
             'italian': 'it',
             'kazakh': 'kk',
             'latvian': 'lv',
             'lithuanian': 'lt',
             'macedonian': 'mk',
             'malay': 'ms',
             'malayalam': 'ml',
             'norwegian': 'no',
             'persian': 'fa',
             'polish': 'pl',
             'portuguese_brazil': 'pt_BR',
             'portuguese_portugal': 'pt_PT',
             'romanian': 'ro',
             'russian': 'ru',
             'serbian': 'sr',
             'slovak': 'sk',
             'slovenian': 'sl',
             'spanish': 'es',
             'swedish': 'sv',
             'tagalog': 'tl',
             'tamil': 'ta',
             'telugu': 'te',
             'turkish': 'tr',
             'ukrainian': 'uk',
             'urdu': 'ur'}

