# -*- coding: utf-8 -*-
# Author: Elizaveta Sineva
"""
ISO 639-1/3 language codes to full language names mapping.
"""

ISO2WIKT = {
            "af": "Afrikaans.af",
            "ak": "Akan.ak",
            "am": "Amharic.am",
            "an": "Aragonese.an",
            "ar": "Arabic.ar",
            "as": "Assamese.as",
            "ast": "Asturian.ast",
            "az": "Azerbaijani.az",
            "ban": "Balinese.ban",
            "be": "Belarusian.be",
            "bg": "Bulgarian.bg",
            "bm": "Bambara.bm",
            "bn": "Bengali.bn",
            "bo": "Tibetan.bo",
            "br": "Breton.br",
            "brx": "Bodo (India).brx",
            "bs": "Serbo-Croatian.sh",
            "ca": "Catalan.ca",
            "ccp": "Chakma.ccp",
            "ce": "Chechen.ce",
            "ceb": "Cebuano.ceb",
            "chr": "Cherokee.chr",
            "ckb": "Central Kurdish.ckb",
            "cs": "Czech.cs",
            "cv": "Chuvash.cv",
            "cy": "Welsh.cy",
            "da": "Danish.da",
            "de": "German.de",
            "dje": "Zarma.dje",
            "dsb": "Lower Sorbian.dsb",
            "dua": "Duala.dua",
            "dyo": "Jola-Fonyi.dyo",
            "dz": "Dzongkha.dz",
            "ee": "Ewe.ee",
            "el": "Greek.el",
            "en": "English.en",
            "eo": "Esperanto.eo",
            "es": "Spanish.es",
            "es_419": "Spanish.es",
            "es_ES": "Spanish.es",
            "et": "Estonian.et",
            "eu": "Basque.eu",
            "fa": "Persian.fa",
            "ff": "Fula.ff",
            "fi": "Finnish.fi",
            "fj": "Fijian.fj",
            "fo": "Faroese.fo",
            "fr": "French.fr",
            "fur": "Friulian.fur",
            "fy": "West Frisian.fy",
            "ga": "Irish.ga",
            "gd": "Scottish Gaelic.gd",
            "gl": "Galician.gl",
            "gsw": "Alemannic German.gsw",
            "gu": "Gujarati.gu",
            "gv": "Manx.gv",
            "ha": "Hausa.ha",
            "haw": "Hawaiian.haw",
            "he": "Hebrew.he",
            "hi": "Hindi.hi",
            "hr": "Serbo-Croatian.sh",
            "hsb": "Upper Sorbian.hsb",
            "hu": "Hungarian.hu",
            "hy": "Armenian.hy",
            "ia": "Interlingua.ia",
            "id": "Indonesian.id",
            "ig": "Igbo.ig",
            "ii": "Nuosu.ii",
            "is": "Icelandic.is",
            "it": "Italian.it",
            "ja": "Japanese.ja",
            "jv": "Javanese.jv",
            "ka": "Georgian.ka",
            "kab": "Kabyle.kab",
            "kam": "Kamba.kam",
            "kea": "Kabuverdianu.kea",
            "kgp": "Kaingang.kgp",
            "khb": "Lü.khb",
            "ki": "Kikuyu.ki",
            "kk": "Kazakh.kk",
            "kl": "Greenlandic.kl",
            "km": "Khmer.km",
            "kn": "Kannada.kn",
            "ko": "Korean.ko",
            "kok": "Konkani.kok",
            "ks": "Kashmiri.ks",
            "ku": "Kurdish.ku",
            "kw": "Cornish.kw",
            "kxv": "Kuvi.kxv",
            "ky": "Kyrgyz.ky",
            "lb": "Luxembourgish.lb",
            "lbj": "Ladakhi.lbj",
            "lg": "Luganda.lg",
            "lij": "Ligurian.lij",
            "lkt": "Lakota.lkt",
            "lmo": "Lombard.lmo",
            "ln": "Lingala.ln",
            "lo": "Lao.lo",
            "lrc": "Northern Luri.lrc",
            "lt": "Lithuanian.lt",
            "luo": "Luo.luo",
            "lv": "Latvian.lv",
            "mai": "Maithili.mai",
            "mer": "Meru.mer",
            "mfe": "Mauritian Creole.mfe",
            "mg": "Malagasy.mg",
            "mi": "Maori.mi",
            "mk": "Macedonian.mk",
            "ml": "Malayalam.ml",
            "mn": "Mongolian.mn",
            "mni": "Manipuri.mni",
            "mr": "Marathi.mr",
            "ms": "Malay.ms",
            "mt": "Maltese.mt",
            "my": "Burmese.my",
            "mzn": "Mazanderani.mzn",
            "naq": "Khoekhoe.naq",
            "nb": "Norwegian Bokmål.nb",
            "nds": "Low German.nds",
            "ne": "Nepali.ne",
            "nl": "Dutch.nl",
            "nn": "Norwegian Nynorsk.nn",
            "no": "Norwegian Inclusive.nor",
            "nod": "Northern Thai.nod",
            "nqo": "N'Ko.nqo",
            "nus": "Nuer.nus",
            "nyn": "Nyankole.nyn",
            "oc": "Occitan.oc",
            "om": "Oromo.om",
            "or": "Odia.or",
            "os": "Ossetian.os",
            "pa": "Punjabi.pa",
            "pcm": "Nigerian Pidgin.pcm",
            "pl": "Polish.pl",
            "prg": "Old Prussian.prg",
            "ps": "Pashto.ps",
            "pt": "Portuguese.pt",
            "pt_BR": "Portuguese.pt",
            "pt_MZ": "Portuguese.pt",
            "pwo": "Western Pwo.pwo",
            "qu": "Quechua.qu",
            "rki": "Rakhine.rki",
            "rm": "Romansch.rm",
            "ro": "Romanian.ro",
            "ru": "Russian.ru",
            "rw": "Rwanda-Rundi.rw",
            "sa": "Sanskrit.sa",
            "sah": "Yakut.sah",
            "sat": "Santali.sat",
            "sc": "Sardinian.sc",
            "sd": "Sindhi.sd",
            "se": "Northern Sami.se",
            "ses": "Koyraboro Senni.ses",
            "sg": "Sango.sg",
            "shi": "Tashelhit.shi",
            "si": "Sinhalese.si",
            "sip": "Sikkimese.sip",
            "sk": "Slovak.sk",
            "sl": "Slovene.sl",
            "sm": "Samoan.sm",
            "smn": "Inari Sami.smn",
            "sn": "Shona.sn",
            "so": "Somali.so",
            "sou": "Southern Thai.sou",
            "sq": "Albanian.sq",
            "sr": "Serbo-Croatian.sh",
            "su": "Sundanese.su",
            "sv": "Swedish.sv",
            "sw": "Swahili.sw",
            "szl": "Silesian.szl",
            "ta": "Tamil.ta",
            "te": "Telugu.te",
            "tg": "Tajik.tg",
            "th": "Thai.th",
            "ti": "Tigrinya.ti",
            "tk": "Turkmen.tk",
            "tl": "Tagalog.tl",
            "to": "Tongan.to",
            "tr": "Turkish.tr",
            "tt": "Tatar.tt",
            "tts": "Isan.tts",
            "tzm": "Central Atlas Tamazight.tzm",
            "ug": "Uyghur.ug",
            "uk": "Ukrainian.uk",
            "ur": "Urdu.ur",
            "urk": "Urak Lawoi'.urk",
            "uz": "Uzbek.uz",
            "vec": "Venetan.vec",
            "vi": "Vietnamese.vi",
            "wo": "Wolof.wo",
            "xh": "Xhosa.xh",
            "xnr": "Kangri.xnr",
            "yi": "Yiddish.yi",
            "yo": "Yoruba.yo",
            "yrl": "Nheengatu.yrl",
            "yue": "Cantonese.yue",
            "za": "Zhuang.za",
            "zh": "Chinese.zh",
            "zh_CN": "Chinese.zh",
            "zh_TW": "Taiwanese Mandarin.goyu",
            "zu": "Zulu.zu"
}
