# -*- coding: utf-8 -*-
# Author: Elizaveta Sineva
"""
ISO 639-1/3 language codes to full language names mapping.
"""

ISO2FULL = {
    "af": "Afrikaans",
    "agq": "Aghem",
    "ak": "Akan",
    "am": "Amharic",
    "an": "Aragonese",
    "ar": "Arabic",
    "as": "Assamese",
    "asa": "Asu",
    "ast": "Asturian",
    "az": "Azerbaijani",
    "ban": "Balinese",
    "bas": "Basaa",
    "be": "Belarusian",
    "bem": "Bemba",
    "bez": "Bena",
    "bg": "Bulgarian",
    "bgc": "Haryanvi",
    "bho": "Bhojpuri",
    "blo": "Anii",
    "bm": "Bambara",
    "bn": "Bengali",
    "bo": "Tibetan",
    "br": "Breton",
    "brx": "Bodo",
    "bs": "Bosnian",
    "ca": "Catalan",
    "ccp": "Chakma",
    "ce": "Chechen",
    "ceb": "Cebuano",
    "cgg": "Chiga",
    "chr": "Cherokee",
    "ckb": "Central Kurdish",
    "cs": "Czech",
    "csw": "Swampy Cree",
    "cv": "Chuvash",
    "cy": "Welsh",
    "da": "Danish",
    "dav": "Taita",
    "de": "German",
    "de_AT": "German (Austria)",
    "de_CH": "German (Switzerland)",
    "de_DE": "German (Germany)",
    "dje": "Zarma",
    "doi": "Dogri",
    "dsb": "Lower Sorbian",
    "dua": "Duala",
    "dyo": "Jola-Fonyi",
    "dz": "Dzongkha",
    "ebu": "Embu",
    "ee": "Ewe",
    "el": "Greek",
    "en": "English",
    "en_AU": "English (Australia)",
    "en_CA": "English (Canada)",
    "en_GB": "English (United Kingdom)",
    "en_US": "English (United States)",
    "en_ZE": "English (Bilingual English-Chinese)",
    "eo": "Esperanto",
    "es": "Spanish",
    "es_419": "Spanish (Latin America)",
    "es_ES": "Spanish (Spain)",
    "es_AR": "Spanish (Argentina)",
    "es_CL": "Spanish (Chile)",
    "et": "Estonian",
    "eu": "Basque",
    "ewo": "Ewondo",
    "fa": "Persian",
    "ff": "Fulah",
    "fi": "Finnish",
    "fil": "Filipino",
    "fj": "Fijian",
    "fo": "Faroese",
    "fr": "French",
    "fr_CH": "French (Switzerland)",
    "fr_FR": "French (France)",
    "fur": "Friulian",
    "fy": "Western Frisian",
    "ga": "Irish",
    "gd": "Scottish Gaelic",
    "gl": "Galician",
    "gn": "Guarani",
    "grb": "Grebo",
    "gsw": "Swiss German",
    "gu": "Gujarati",
    "guz": "Gusii",
    "gv": "Manx",
    "ha": "Hausa",
    "haw": "Hawaiian",
    "he": "Hebrew",
    "hi": "Hindi",
    "hr": "Croatian",
    "hsb": "Upper Sorbian",
    "hu": "Hungarian",
    "hy": "Armenian",
    "ia": "Interlingua",
    "id": "Indonesian",
    "ie": "Interlingue",
    "ig": "Igbo",
    "ii": "Sichuan Yi",
    "is": "Icelandic",
    "it": "Italian",
    "ja": "Japanese",
    "jgo": "Ngomba",
    "jmc": "Machame",
    "jv": "Javanese",
    "ka": "Georgian",
    "kab": "Kabyle",
    "kam": "Kamba",
    "kar": "Karen",
    "kde": "Makonde",
    "kea": "Kabuverdianu",
    "kgp": "Kaingang",
    "khb": "Tai Lue",
    "khq": "Koyra Chiini",
    "ki": "Kikuyu",
    "kk": "Kazakh",
    "kkj": "Kako",
    "kl": "Kalaallisut",
    "kln": "Kalenjin",
    "km": "Khmer",
    "kn": "Kannada",
    "ko": "Korean",
    "kok": "Konkani",
    "ks": "Kashmiri",
    "ksb": "Shambala",
    "ksf": "Bafia",
    "ksh": "Colognian",
    "ku": "Kurdish",
    "kw": "Cornish",
    "kxv": "Kuvi",
    "ky": "Kyrgyz",
    "lag": "Langi",
    "lb": "Luxembourgish",
    "lbj": "Ladakhi",
    "lg": "Ganda",
    "lij": "Ligurian",
    "lkt": "Lakota",
    "lmo": "Lombard",
    "ln": "Lingala",
    "lo": "Lao",
    "lrc": "Northern Luri",
    "lt": "Lithuanian",
    "lu": "Luba-Katanga",
    "luo": "Luo",
    "luy": "Luyia",
    "lv": "Latvian",
    "mai": "Maithili",
    "mas": "Masai",
    "mer": "Meru",
    "mfe": "Mauritian Creole",
    "mg": "Malagasy",
    "mgh": "Makhuwa-Meetto",
    "mgo": "Meta'",
    "mi": "Māori",
    "mk": "Macedonian",
    "ml": "Malayalam",
    "mn": "Mongolian",
    "mni": "Manipuri",
    "mr": "Marathi",
    "ms": "Malay",
    "mt": "Maltese",
    "mua": "Mundang",
    "my": "Burmese",
    "mzn": "Mazanderani",
    "naq": "Nama",
    "nb": "Norwegian Bokmal",
    "nd": "North Ndebele",
    "nds": "Low German",
    "ne": "Nepali",
    "nl": "Dutch",
    "nmg": "Kwasio",
    "nn": "Norwegian Nynorsk",
    "nnh": "Ngiemboon",
    "no": "Norwegian",
    "nod": "Northern Thai",
    "nqo": "N'Ko",
    "nus": "Nuer",
    "nyn": "Nyankole",
    "oc": "Occitan",
    "om": "Oromo",
    "or": "Odia",
    "os": "Ossetian",
    "pa": "Punjabi",
    "pcm": "Nigerian Pidgin",
    "pht": "Phu Thai", 
    "phu": "Phuan",
    "pl": "Polish",
    "prg": "Prussian",
    "ps": "Pashto",
    "pt": "Portuguese",
    "pt_BR": "Portuguese (Brazil)",
    "pt_MZ": "Portuguese (Mozambique)",
    "pt_PT": "Portuguese (Portugal)",
    "pwo": "Pwo Western Karen",
    "qu": "Quechua",
    "raj": "Rajasthani",
    "rki": "Rakhine",
    "rm": "Romansh",
    "rmz": "Marma",
    "rn": "Rundi",
    "ro": "Romanian",
    "rof": "Rombo",
    "ru": "Russian",
    "rw": "Kinyarwanda",
    "rwk": "Rwa",
    "sa": "Sanskrit",
    "sah": "Sakha",
    "saq": "Samburu",
    "sat": "Santali",
    "sbp": "Sangu",
    "sc": "Sardinian",
    "sd": "Sindhi",
    "se": "Northern Sami",
    "seh": "Sena",
    "ses": "Koyraboro Senni",
    "sg": "Sango",
    "shi": "Tachelhit",
    "si": "Sinhala",
    "sip": "Sikkimese",
    "sk": "Slovak",
    "sk_SK": "Slovak (Slovakia)",
    "sl": "Slovenian",
    "sm": "Samoan",
    "smn": "Inari Sami",
    "sn": "Shona",
    "so": "Somali",
    "sou": "Southern Thai",
    "sq": "Albanian",
    "sr": "Serbian",
    "su": "Sundanese",
    "sv": "Swedish",
    "sw": "Swahili",
    "syr": "Syriac",
    "szl": "Silesian",
    "ta": "Tamil",
    "te": "Telugu",
    "teo": "Teso",
    "tg": "Tajik",
    "th": "Thai",
    "ti": "Tigrinya",
    "tk": "Turkmen",
    "to": "Tongan",
    "tok": "Toki Pona",
    "tl": "Tagalog",
    "tr": "Turkish",
    "tt": "Tatar",
    "tts": "Northeastern Thai",
    "twq": "Tasawaq",
    "tzm": "Central Atlas Tamazight",
    "ug": "Uyghur",
    "uk": "Ukrainian",
    "umb": "Umbundu",
    "ur": "Urdu",
    "urk": "Urak Lawoi'",
    "uz": "Uzbek",
    "vai": "Vai",
    "vec": "Venetian",
    "vi": "Vietnamese",
    "vmw": "Makhuwa",
    "vun": "Vunjo",
    "wae": "Walser",
    "wo": "Wolof",
    "xh": "Xhosa",
    "xnr": "Kangri",
    "xog": "Soga",
    "yav": "Yangben",
    "yi": "Yiddish",
    "yo": "Yoruba",
    "yrl": "Nheengatu",
    "yue": "Cantonese",
    "za": "Zhuang",
    "zau": "Zangskari",
    "zgh": "Standard Moroccan Tamazight",
    "zh": "Chinese",
    "zh_CN": "Chinese (Mainland China)",
    "zh_TW": "Chinese (Taiwan)",
    "zh_ZE": "Chinese (Bilingual Chinese-English)",
    "zu": "Zulu",
}
