# -*- coding: utf-8 -*-
# Author: Elizaveta Sineva
"""
Configuration and constants for the FILMSer tools.
"""

from src.filmser.lang_dicts.iso2full import ISO2FULL
from src.filmser.lang_dicts.full2iso import FULL2ISO
from src.filmser.lang_dicts.iso2wikt import ISO2WIKT

# Default settings
DEFAULT_SPACY_SIZE = "sm"
DEFAULT_OUTPUT_DIR = "data/"
DEFAULT_OUTPUT_TYPE = "tsv|xlsx"

# Linguistic feature colum order
LING_FEATURES = ["Lemma", "PoS (UPOS)", "PoS (language-specific)", "Morphological features", "Stop word"]

# N-gram name mappings
NGRAM_NAMES = {1: "unigram", 2: "bigram", 3: "trigram", 4: "quadgram"}

# Supported output formats
VALID_OUTPUT_FORMATS = {"txt", "tsv", "csv", "xlsx", "json"}

# Preferred spell-checker providers for languages with correct spell-checker tag(s)
ENCHANT2PROVIDER2TAG = {
	'af': ('Hunspell', ['af_ZA']),
	'am': ('Aspell', ['am']),
	'an': ('Hunspell', ['an_ES']),
	'ar': ('Aspell', ['ar']),
	'as': ('Hunspell', ['as_IN']),
	'ast': ('Aspell', ['ast']),
	'az': ('Aspell', ['az']),
	'be': ('Aspell', ['be']),
	'bg': ('Hunspell', ['bg_BG']),
	'bn': ('Aspell', ['bn']),
	'br': ('Hunspell', ['br_FR']),
	'bs': ('Hunspell', ['bs_BA']),
	'ca': ('Hunspell', ['ca']),
	'cs': ('Hunspell', ['cs_CZ']),
	'cy': ('Aspell', ['cy']),
	'da': ('Hunspell', ['da_DK']),
	'de': ('Hunspell', ['de_DE', 'de_AT', 'de_CH']),
	'el': ('Hunspell', ['el_GR']),
	'en': ('Hunspell', ['en_US', 'en_GB', 'en_CA', 'en_ZA']),
	'eo': ('Hunspell', ['eo']),
	'es': ('Hunspell', ['es_ES']),
	'et': ('Aspell', ['et']),
	'eu': ('Hunspell', ['eu']),
	'fa': ('Aspell', ['fa']),
	'fi': ('Voikko', ['fi']),
	'fr': ('Hunspell', ['fr']),
	'ga': ('Aspell', ['ga']),
	'gd': ('Hunspell', ['gd_GB']),
	'gl': ('Hunspell', ['gl_ES']),
	'he': ('Hunspell', ['he_IL']),
	'hi': ('Aspell', ['hi']),
	'hr': ('Aspell', ['hr']),
	'hu': ('Aspell', ['hu']),
	'hy': ('Aspell', ['hy']),
	'id': ('Hunspell', ['id_ID']),
	'is': ('Aspell', ['is']),
	'it': ('Hunspell', ['it_IT']),
	'kk': ('Hunspell', ['kk_KZ']),
	'kn': ('Aspell', ['kn']),
	'ko': ('Hunspell', ['ko']),
	'ku': ('Hunspell', ['ku_TR']),
	'lt': ('Hunspell', ['lt_LT']),
	'lv': ('Hunspell', ['lv_LV']),
	'mk': ('Aspell', ['mk']),
	'ml': ('Hunspell', ['ml_IN']),
	'mn': ('Hunspell', ['mn_MN']),
	'mr': ('Hunspell', ['mr']),
	'ms': ('Aspell', ['ms']),
	'nb': ('Hunspell', ['nb_NO']),
	'ne': ('Hunspell', ['ne_NP']),
	'nl': ('Hunspell', ['nl']),
	'nn': ('Hunspell', ['nn_NO']),
	'no': ('Hunspell', ['nb_NO', 'nn_NO']),
	'oc': ('Hunspell', ['oc_FR']),
	'or': ('Aspell', ['or']),
	'pl': ('Hunspell', ['pl_PL']),
	'pt': ('Hunspell', ['pt_BR', 'pt_PT']),
	'pt_BR': ('Hunspell', ['pt_PT']),
	'pt_PT': ('Hunspell', ['pt_BR']),
	'ro': ('Hunspell', ['ro_RO']),
	'ru': ('Hunspell', ['ru_RU']),
	'se': ('Voikko', ['fi']),
	'si': ('Hunspell', ['si_LK']),
	'sk': ('Hunspell', ['sk_SK']),
	'sl': ('Hunspell', ['sl_SI']),
	'sq': ('Hunspell', ['sq_AL']),
	'sr': ('Hunspell', ['sr_RS', 'sr_Latn_RS']),
	'sv': ('Hunspell', ['sv_FI', 'sv_SE']),
	'sw': ('Hunspell', ['sw_TZ']),
	'ta': ('Aspell', ['ta']),
	'te': ('Aspell', ['te']),
	'th': ('Hunspell', ['th_TH']),
	'tl': ('Hunspell', ['tl']),
	'tr': ('Hunspell', ['tr_TR']),
	'uk': ('Hunspell', ['uk_UA']),
	'uz': ('Hunspell', ['uz_UZ']),
	'vi': ('Aspell', ['vi']),
}

# Spacy model sizes
SIZE2SPACY = {"small": "sm",
              "medium": "md",
              "middle": "md", 
              "large": "lg",
              "big": "lg",
              "transformer": "trf",
              "transformers": "trf"}

# Supported spacy languages
SPACY_LANG = {'ca', 'da', 'de', 'el', 'en', 'es', 'fi', 'fr', 'hr', 'it', 'ja', 'ko', 
              'lt', 'mk', 'nb', 'nl', 'pl', 'pt', 'ro', 'ru', 'sl', 'sv', 'uk', 'zh'}

# Language code adaptations for spacy
LANG2SPACYLANG = {
    "no": "nb",
    "yue": "zh"
}

# Languages that do not use word boundaries
NON_WORD_BOUND = {'ban', 'bo', 'dz', 'ja', 'kar', 'khb', 'km', 'ko', 'lbj', 'lo', 'my', 'nod', 'pht', 'phu',
                  'pwo', 'rki', 'rmz', 'sip', 'sou', 'th', 'tts', 'urk', 'vi', 'yue', 'za', 'zau', 'zh'}

# Languages that do not use word boundaries and are supported by ICU tokenizer
NON_WORD_BOUND_IN_ICU = {'bo', 'dz', 'ja', 'km', 'ko', 'lo', 'my', 'th', 'vi', 'yue', 'za', 'zh'}

# Mapping from ISO 639-1/3 language codes to ICU locale postfixes
ICU_LANG2POSTFIX = {
	'af': ['NA', 'ZA'],
	'agq': ['CM'],
	'ak': ['GH'],
	'am': ['ET'],
	'ar': ['001', 'AE', 'BH', 'DJ', 'DZ', 'EG', 'EH', 'ER', 'IL', 'IQ', 'JO', 
           'KM', 'KW', 'LB', 'LY', 'MA', 'MR', 'OM', 'PS', 'QA', 'SA', 'SD', 
           'SO', 'SS', 'SY', 'TD', 'TN', 'YE'],
	'as': ['IN'],
	'asa': ['TZ'],
	'ast': ['ES'],
	'az': ['Cyrl', 'Cyrl_AZ', 'Latn', 'Latn_AZ'],
	'bas': ['CM'],
	'be': ['BY'],
	'bem': ['ZM'],
	'bez': ['TZ'],
	'bg': ['BG'],
	'bgc': ['IN'],
	'bho': ['IN'],
	'blo': ['BJ'],
	'bm': ['ML'],
	'bn': ['BD', 'IN'],
	'bo': ['CN', 'IN'],
	'br': ['FR'],
	'brx': ['IN'],
	'bs': ['Cyrl', 'Cyrl_BA', 'Latn', 'Latn_BA'],
	'ca': ['AD', 'ES', 'FR', 'IT'],
	'ccp': ['BD', 'IN'],
	'ce': ['RU'],
	'ceb': ['PH'],
	'cgg': ['UG'],
	'chr': ['US'],
	'ckb': ['IQ', 'IR'],
	'cs': ['CZ'],
	'csw': ['CA'],
	'cv': ['RU'],
	'cy': ['GB'],
	'da': ['DK', 'GL'],
	'dav': ['KE'],
	'de': ['AT', 'BE', 'CH', 'DE', 'IT', 'LI', 'LU'],
	'dje': ['NE'],
	'doi': ['IN'],
	'dsb': ['DE'],
	'dua': ['CM'],
	'dyo': ['SN'],
	'dz': ['BT'],
	'ebu': ['KE'],
	'ee': ['GH', 'TG'],
	'el': ['CY', 'GR'],
	'en': ['001', '150', 'AE', 'AG', 'AI', 'AS', 'AT', 'AU', 'BB', 'BE', 'BI',
          'BM', 'BS', 'BW', 'BZ', 'CA', 'CC', 'CH', 'CK', 'CM', 'CX', 'CY', 'DE', 
          'DG', 'DK', 'DM', 'ER', 'FI', 'FJ', 'FK', 'FM', 'GB', 'GD', 'GG', 'GH', 
          'GI', 'GM', 'GU', 'GY', 'HK', 'ID', 'IE', 'IL', 'IM', 'IN', 'IO', 'JE', 
          'JM', 'KE', 'KI', 'KN', 'KY', 'LC', 'LR', 'LS', 'MG', 'MH', 'MO', 'MP', 
          'MS', 'MT', 'MU', 'MV', 'MW', 'MY', 'NA', 'NF', 'NG', 'NL', 'NR', 'NU', 
          'NZ', 'PG', 'PH', 'PK', 'PN', 'PR', 'PW', 'RW', 'SB', 'SC', 'SD', 'SE', 
          'SG', 'SH', 'SI', 'SL', 'SS', 'SX', 'SZ', 'TC', 'TK', 'TO', 'TT', 'TV', 
          'TZ', 'UG', 'UM', 'US', 'US_POSIX', 'VC', 'VG', 'VI', 'VU', 'WS', 'ZA', 
          'ZM', 'ZW'],
	'eo': ['001'],
	'es': ['419', 'AR', 'BO', 'BR', 'BZ', 'CL', 'CO', 'CR', 'CU', 'DO', 'EA', 'EC', 
           'ES', 'GQ', 'GT', 'HN', 'IC', 'MX', 'NI', 'PA', 'PE', 'PH', 'PR', 'PY', 
           'SV', 'US', 'UY', 'VE'],
	'et': ['EE'],
	'eu': ['ES'],
	'ewo': ['CM'],
	'fa': ['AF', 'IR'],
	'ff': ['Adlm', 'Adlm_BF', 'Adlm_CM', 'Adlm_GH', 'Adlm_GM', 'Adlm_GN', 'Adlm_GW', 
           'Adlm_LR', 'Adlm_MR', 'Adlm_NE', 'Adlm_NG', 'Adlm_SL', 'Adlm_SN', 'Latn', 
           'Latn_BF', 'Latn_CM', 'Latn_GH', 'Latn_GM', 'Latn_GN', 'Latn_GW', 'Latn_LR',
           'Latn_MR', 'Latn_NE', 'Latn_NG', 'Latn_SL', 'Latn_SN'],
	'fi': ['FI'],
	'fil': ['PH'],
	'fo': ['DK', 'FO'],
	'fr': ['BE', 'BF', 'BI', 'BJ', 'BL', 'CA', 'CD', 'CF', 'CG', 'CH', 'CI', 'CM', 'DJ', 
           'DZ', 'FR', 'GA', 'GF', 'GN', 'GP', 'GQ', 'HT', 'KM', 'LU', 'MA', 'MC', 'MF', 
           'MG', 'ML', 'MQ', 'MR', 'MU', 'NC', 'NE', 'PF', 'PM', 'RE', 'RW', 'SC', 'SN', 
           'SY', 'TD', 'TG', 'TN', 'VU', 'WF', 'YT'],
	'fur': ['IT'],
	'fy': ['NL'],
	'ga': ['GB', 'IE'],
	'gd': ['GB'],
	'gl': ['ES'],
	'gsw': ['CH', 'FR', 'LI'],
	'gu': ['IN'],
	'guz': ['KE'],
	'gv': ['IM'],
	'ha': ['GH', 'NE', 'NG'],
	'haw': ['US'],
	'he': ['IL'],
	'hi': ['IN', 'Latn', 'Latn_IN'],
	'hr': ['BA', 'HR'],
	'hsb': ['DE'],
	'hu': ['HU'],
	'hy': ['AM'],
	'ia': ['001'],
	'id': ['ID'],
	'ie': ['EE'],
	'ig': ['NG'],
	'ii': ['CN'],
	'is': ['IS'],
	'it': ['CH', 'IT', 'SM', 'VA'],
	'ja': ['JP'],
	'jgo': ['CM'],
	'jmc': ['TZ'],
	'jv': ['ID'],
	'ka': ['GE'],
	'kab': ['DZ'],
	'kam': ['KE'],
	'kde': ['TZ'],
	'kea': ['CV'],
	'kgp': ['BR'],
	'khq': ['ML'],
	'ki': ['KE'],
	'kk': ['KZ'],
	'kkj': ['CM'],
	'kl': ['GL'],
	'kln': ['KE'],
	'km': ['KH'],
	'kn': ['IN'],
	'ko': ['CN', 'KP', 'KR'],
	'kok': ['IN'],
	'ks': ['Arab', 'Arab_IN', 'Deva', 'Deva_IN'],
	'ksb': ['TZ'],
	'ksf': ['CM'],
	'ksh': ['DE'],
	'ku': ['TR'],
	'kw': ['GB'],
	'kxv': ['Deva', 'Deva_IN', 'Latn', 'Latn_IN', 'Orya', 'Orya_IN', 'Telu', 'Telu_IN'],
	'ky': ['KG'],
	'lag': ['TZ'],
	'lb': ['LU'],
	'lg': ['UG'],
	'lij': ['IT'],
	'lkt': ['US'],
	'lmo': ['IT'],
	'ln': ['AO', 'CD', 'CF', 'CG'],
	'lo': ['LA'],
	'lrc': ['IQ', 'IR'],
	'lt': ['LT'],
	'lu': ['CD'],
	'luo': ['KE'],
	'luy': ['KE'],
	'lv': ['LV'],
	'mai': ['IN'],
	'mas': ['KE', 'TZ'],
	'mer': ['KE'],
	'mfe': ['MU'],
	'mg': ['MG'],
	'mgh': ['MZ'],
	'mgo': ['CM'],
	'mi': ['NZ'],
	'mk': ['MK'],
	'ml': ['IN'],
	'mn': ['MN'],
	'mni': ['Beng', 'Beng_IN'],
	'mr': ['IN'],
	'ms': ['BN', 'ID', 'MY', 'SG'],
	'mt': ['MT'],
	'mua': ['CM'],
	'my': ['MM'],
	'mzn': ['IR'],
	'naq': ['NA'],
	'nb': ['NO', 'SJ'],
	'nd': ['ZW'],
	'nds': ['DE', 'NL'],
	'ne': ['IN', 'NP'],
	'nl': ['AW', 'BE', 'BQ', 'CW', 'NL', 'SR', 'SX'],
	'nmg': ['CM'],
	'nn': ['NO'],
	'nnh': ['CM'],
	'no': [],
	'nqo': ['GN'],
	'nus': ['SS'],
	'nyn': ['UG'],
	'oc': ['ES', 'FR'],
	'om': ['ET', 'KE'],
	'or': ['IN'],
	'os': ['GE', 'RU'],
	'pa': ['Arab', 'Arab_PK', 'Guru', 'Guru_IN'],
	'pcm': ['NG'],
	'pl': ['PL'],
	'prg': ['PL'],
	'ps': ['AF', 'PK'],
	'pt': ['AO', 'BR', 'CH', 'CV', 'GQ', 'GW', 'LU', 'MO', 'MZ', 'PT', 'ST', 'TL'],
	'qu': ['BO', 'EC', 'PE'],
	'raj': ['IN'],
	'rm': ['CH'],
	'rn': ['BI'],
	'ro': ['MD', 'RO'],
	'rof': ['TZ'],
	'ru': ['BY', 'KG', 'KZ', 'MD', 'RU', 'UA'],
	'rw': ['RW'],
	'rwk': ['TZ'],
	'sa': ['IN'],
	'sah': ['RU'],
	'saq': ['KE'],
	'sat': ['Olck', 'Olck_IN'],
	'sbp': ['TZ'],
	'sc': ['IT'],
	'sd': ['Arab', 'Arab_PK', 'Deva', 'Deva_IN'],
	'se': ['FI', 'NO', 'SE'],
	'seh': ['MZ'],
	'ses': ['ML'],
	'sg': ['CF'],
	'shi': ['Latn', 'Latn_MA', 'Tfng', 'Tfng_MA'],
	'si': ['LK'],
	'sk': ['SK'],
	'sl': ['SI'],
	'smn': ['FI'],
	'sn': ['ZW'],
	'so': ['DJ', 'ET', 'KE', 'SO'],
	'sq': ['AL', 'MK', 'XK'],
	'sr': ['Cyrl', 'Cyrl_BA', 'Cyrl_ME', 'Cyrl_RS', 'Cyrl_XK', 'Latn', 'Latn_BA', 'Latn_ME', 'Latn_RS', 'Latn_XK'],
	'su': ['Latn', 'Latn_ID'],
	'sv': ['AX', 'FI', 'SE'],
	'sw': ['CD', 'KE', 'TZ', 'UG'],
	'syr': ['IQ', 'SY'],
	'szl': ['PL'],
	'ta': ['IN', 'LK', 'MY', 'SG'],
	'te': ['IN'],
	'teo': ['KE', 'UG'],
	'tg': ['TJ'],
	'th': ['TH'],
	'ti': ['ER', 'ET'],
	'tk': ['TM'],
	'to': ['TO'],
	'tok': ['001'],
	'tr': ['CY', 'TR'],
	'tt': ['RU'],
	'twq': ['NE'],
	'tzm': ['MA'],
	'ug': ['CN'],
	'uk': ['UA'],
	'ur': ['IN', 'PK'],
	'uz': ['Arab', 'Arab_AF', 'Cyrl', 'Cyrl_UZ', 'Latn', 'Latn_UZ'],
	'vai': ['Latn', 'Latn_LR', 'Vaii', 'Vaii_LR'],
	'vec': ['IT'],
	'vi': ['VN'],
	'vmw': ['MZ'],
	'vun': ['TZ'],
	'wae': ['CH'],
	'wo': ['SN'],
	'xh': ['ZA'],
	'xnr': ['IN'],
	'xog': ['UG'],
	'yav': ['CM'],
	'yi': ['UA'],
	'yo': ['BJ', 'NG'],
	'yrl': ['BR', 'CO', 'VE'],
	'yue': ['Hans', 'Hans_CN', 'Hant', 'Hant_HK'],
	'za': ['CN'],
	'zgh': ['MA'],
	'zh': ['Hans', 'Hans_CN', 'Hans_HK', 'Hans_MO', 'Hans_SG', 'Hant', 'Hant_HK', 'Hant_MO', 'Hant_TW'],
	'zu': ['ZA']
}
