# -*- coding: utf-8 -*-
# Authors: Elizaveta Sineva, Sara Chilson
"""
Dictionaries converting ISO language codes to full language name and vice
versa.
"""


ISO2FULL = {"af": "Afrikaans",
            "am": "Amharic",
            "an": "Aragonese",
            "ar": "Arabic",
            "as": "Assamese",
            "ast": "Asturian",
            "az": "Azerbaijani",
            "be": "Belarusian",
            "bg": "Bulgarian",
            "bn": "Bengali",
            "br": "Breton",
            "bs": "Bosnian",
            "ca": "Catalan",
            "cs": "Czech",
            "cy": "Welsh",
            "da": "Danish",
            "de": "German",
            "eu": "Basque",
            "el": "Greek",
            "en": "English",
            "eo": "Esperanto",
            "es": "Spanish",
            "es_419": "Latin American Spanish",
            "es_es": "European Spanish",
            "et": "Estonian",
            "fa": "Persian",
            "fi": "Finnish",
            "fr": "French",
            "ga": "Irish",
            "gd": "Scottish Gaelic",
            "gl": "Galician",
            "he": "Hebrew",
            "hi": "Hindi",
            "hr": "Croatian",
            "hu": "Hungarian",
            "hy": "Armenian",
            "id": "Indonesian",
            "ig": "Igbo",
            "is": "Icelandic",
            "it": "Italian",
            "ja": "Japanese",
            "ka": "Georgian",
            "kk": "Kazakh",
            "km": "Khmer",
            "kn": "Kannada",
            "ko": "Korean",
            "ku": "Kurdish",
            "lb": "Luxembourgish",
            "lt": "Lithuanian",
            "lv": "Latvian",
            "mk": "Macedonian",
            "ml": "Malayalam",
            "mn": "Mongolian",
            "mr": "Marathi",
            "ms": "Malay",
            "my": "Burmese",
            "ne": "Nepali",
            "nl": "Dutch",
            "no": "Norwegian",
            "nb": "Norwegian Bokmal",
            "nn": "Norwegian Nynorsk",
            "oc": "Occitan",
            "or": "Odia",
            "pl": "Polish",
            "pt": "Portuguese",
            "pt_br": "Brazilian Portuguese",
            "pt_mz": "Mozambican Portuguese",
            "pt_pt": "European Portuguese",
            "ro": "Romanian",
            "ru": "Russian",
            "sd": "Sindhi",
            "se": "Northern Sami",
            "si": "Sinhala",
            "sk": "Slovak",
            "sl": "Slovenian",
            "so": "Somali",
            "sq": "Albanian",
            "sr": "Serbian",
            "sv": "Swedish",
            "sw": "Swahili",
            "ta": "Tamil",
            "te": "Telugu",
            "th": "Thai",
            "tl": "Tagalog",
            "tr": "Turkish",
            "tt": "Tatar",
            "uk": "Ukrainian",
            "ur": "Urdu",
            "vi": "Vietnamese",
            "yue": "Cantonese",
            "zh": "Chinese",
            "zh_cn": "Mainland Chinese",
            "zh_tw": "Taiwanese Chinese"}



FULL2ISO = {"afrikaans": "af",
            "albanian": "sq",
            "amharic": "am",
            "arabic": "ar",
            "aragonese": "an",
            "armenian": "hy",
            "assamese": "as",
            "asturian": "ast",
            "azerbaijani": "az",
            "basque": "eu",
            "belarusian": "be",
            "bengali": "bn",
            "bosnian": "bs",
            "breton": "br",
            "bulgarian": "bg",
            "burmese": "my",
            "cantonese": "yue",
            "catalan": "ca",
            "chinese": "zh",
            "mainland_chinese": "zh_CN",
            "taiwanese_chinese": "zh_TW",
            "croatian": "hr",
            "czech": "cs",
            "danish": "da",
            "dutch": "nl",
            "english": "en",
            "esperanto": "eo",
            "estonian": "et",
            "finnish": "fi",
            "french": "fr",
            "galician": "gl",
            "georgian": "ka",
            "german": "de",
            "greek": "el",
            "hebrew": "he",
            "hindi": "hi",
            "hungarian": "hu",
            "icelandic": "is",
            "igbo": "ig",
            "indonesian": "id",
            "irish": "ga",
            "italian": "it",
            "japanese": "ja",
            "kannada": "kn",
            "kazakh": "kk",
            "khmer": "km",
            "korean": "ko",
            "kurdish": "ku",
            "latvian": "lv",
            "lithuanian": "lt",
            "luxembourgish": "lb",
            "macedonian": "mk",
            "malay": "ms",
            "malayalam": "ml",
            "marathi": "mr",
            "mongolian": "mn",
            "nepali": "ne",
            "northern_sami": "se",
            "norwegian": "no",
            "norwegian_bokmal": "nb",
            "norwegian_nynorsk": "nn",
            "occitan": "oc",
            "odia": "or",
            "persian": "fa",
            "polish": "pl",
            "portuguese": "pt",
            "brazilian_portuguese": "pt_BR",
            "european_portuguese": "pt_PT",
            "mozambican_portuguese": "pt_MZ",
            "romanian": "ro",
            "russian": "ru",
            "scottish_gaelic": "gd",
            "serbian": "sr",
            "sindhi": "sd",
            "sinhala": "si",
            "slovak": "sk",
            "slovenian": "sl",
            "somali": "so",
            "spanish": "es",
            "european_spanish": "es_ES",
            "latin_american_spanish": "es_419",
            "swahili": "sw",
            "swedish": "sv",
            "tagalog": "tl",
            "tamil": "ta",
            "tatar": "tt",
            "telugu": "te",
            "thai": "th",
            "turkish": "tr",
            "ukrainian": "uk",
            "urdu": "ur",
            "vietnamese": "vi",
            "welsh": "cy"}

